### PR TITLE
Fix wrong read / write positions for PlayClientLook and PlayClientPositionLook

### PR DESCRIPTION
**Pull request by Janmm14**
This bug was present since the initial 1.8 update, reading all the values from position zero rather than the real position.

PacketPlayClientLook:
 - pitch 0 -> 1

PacketPlayClientPositionLook:
 - y 0 -> 1
 - z 0 -> 2
 - pitch 0 -> 1

### CODE REVIEW

**Comment by Janmm14** [comment]
just saw this high diff, will cut down soon

**Comment by dmulloy2** [comment]
Line endings are a real pain

**Comment by Janmm14** [comment]
@dmulloy2 I'm sorry, but I do not get the line endings correctly. Please do that yourself.

**Comment by Janmm14** [comment]
@dmulloy2

**Pull request closed without merging**
